return {
  --   'nvim-telescope/telescope.nvim',
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --     'nvim-telescope/telescope-ui-select.nvim',
  --     "debugloop/telescope-undo.nvim",
  --     'kyazdani42/nvim-web-devicons',
  --   },
  --   config = function()
  --     local telescope = require("telescope")
  --
  --
  --     telescope.setup {
  --       defaults = {
  --         -- shorten_path = { true },
  --         path_display = { "smart" },
  --         preview = { true },
  --         file_ignore_patterns = { 'node_modules', 'vendor' },
  --       },
  --       pickers = {
  --         find_files = {
  --           prompt_title = 'All Files',
  --         },
  --         current_buffer_fuzzy_find = {
  --           prompt_title = 'Current buffer',
  --         },
  --         oldfiles = {
  --           sort_lastused = true,
  --           prompt_title = "Recently Opened",
  --         },
  --         buffers = {
  --           sort_lastused = true,
  --           mappings = {
  --             i = {
  --               ["<c-d>"] = "delete_buffer",
  --             }
  --           }
  --         }
  --       },
  --       extensions = {
  --         ["ui-select"] = {
  --           require("telescope.themes").get_dropdown {}
  --         },
  --         undo = {
  --           -- telescope-undo.nvim config, see below
  --         },
  --
  --       }
  --     }
  --     telescope.load_extension("ui-select")
  --     telescope.load_extension("undo")
  --   end
}
